all:
	$(MAKE) -C oscillator
	$(MAKE) -C filter
	$(MAKE) -C looper
	$(MAKE) -C dusting
	$(MAKE) -C calibrator

clean:
	$(MAKE) -C oscillator clean
	$(MAKE) -C filter clean
	$(MAKE) -C looper clean
	$(MAKE) -C dusting clean
	$(MAKE) -C calibrator clean
