all:
	$(MAKE) -C calibrator
	$(MAKE) -C chorus
	$(MAKE) -C dusting
	$(MAKE) -C filter
	$(MAKE) -C looper
	$(MAKE) -C oscillator
	$(MAKE) -C reverb/1962a
	$(MAKE) -C reverb/1962b
	$(MAKE) -C reverb/1962c

clean:
	$(MAKE) -C calibrator clean
	$(MAKE) -C chorus clean
	$(MAKE) -C dusting clean
	$(MAKE) -C filter clean
	$(MAKE) -C looper clean
	$(MAKE) -C oscillator clean
	$(MAKE) -C reverb/1962a clean
	$(MAKE) -C reverb/1962b clean
	$(MAKE) -C reverb/1962c clean
