all:
	$(MAKE) -C calibrator
	$(MAKE) -C chorus
	$(MAKE) -C dusting
	$(MAKE) -C filter
	$(MAKE) -C looper
	$(MAKE) -C oscillator
	$(MAKE) -C reverb
clean:
	$(MAKE) -C calibrator clean
	$(MAKE) -C chorus clean
	$(MAKE) -C dusting clean
	$(MAKE) -C filter clean
	$(MAKE) -C looper clean
	$(MAKE) -C oscillator clean
	$(MAKE) -C reverb clean
