all:
	$(MAKE) -C bluemchen
	$(MAKE) -C dpt
	$(MAKE) -C lichen-bifocals
	$(MAKE) -C lichen-freddie
	$(MAKE) -C lichen-medium
	$(MAKE) -C patch_init
	$(MAKE) -C versio

clean:
	$(MAKE) -C bluemchen clean
	$(MAKE) -C dpt clean
	$(MAKE) -C lichen-bifocals clean
	$(MAKE) -C lichen-freddie clean
	$(MAKE) -C lichen-medium clean
	$(MAKE) -C patch_init clean
	$(MAKE) -C versio clean
