interface Signals {
    star_sig_Value Value_new(star_Allocator allocator,
        star_AudioSettings audioSettings);

    void Value_destroy(star_Allocator allocator,
        star_sig_Value value);


    star_sig_BinaryOp_Inputs BinaryOp_Inputs_new(star_Allocator allocator,
        any left, any right);

    void BinaryOp_Inputs_destroy(star_Allocator allocator,
        star_sig_BinaryOp_Inputs inputs);

    star_sig_BinaryOp Mul_new(star_Allocator allocator,
        star_AudioSettings audioSettings,
        star_sig_BinaryOp_Inputs inputs);

    void Mul_destroy(star_Allocator allocator, star_sig_BinaryOp mul);

    star_sig_BinaryOp Add_new(star_Allocator allocator,
        star_AudioSettings audioSettings,
        star_sig_BinaryOp_Inputs inputs);

    void Add_destroy(star_Allocator allocator, star_sig_BinaryOp add);

    star_sig_BinaryOp Div_new(star_Allocator allocator,
        star_AudioSettings audioSettings,
        star_sig_BinaryOp_Inputs inputs);

    void Div_destroy(star_Allocator allocator, star_sig_BinaryOp div);


    star_sig_Sine Sine_new(star_Allocator allocator,
        star_AudioSettings audioSettings,
        star_sig_Sine_Inputs inputs);

    void Sine_destroy(star_Allocator allocator,
        star_sig_Sine sine);

    star_sig_Sine_Inputs Sine_Inputs_new(star_Allocator allocator,
        any freq, any phaseOffset, any mul, any add);

    void Sine_Inputs_destroy(star_Allocator allocator,
        star_sig_Sine_Inputs inputs);


    star_sig_ClockFreqDetector ClockFreqDetector_new(star_Allocator allocator,
        star_AudioSettings audioSettings,
        star_sig_ClockFreqDetector_Inputs inputs);

    void ClockFreqDetector_destroy(star_Allocator allocator,
        star_sig_ClockFreqDetector detector);

    star_sig_ClockFreqDetector_Inputs ClockFreqDetector_Inputs_new(star_Allocator allocator, any source);

    void ClockFreqDetector_Inputs_destroy(star_Allocator allocator,
        star_sig_ClockFreqDetector_Inputs inputs);
};

interface Starlings {
    readonly attribute float PI;
    readonly attribute float TWOPI;

    void Starlings();

    [Value] attribute Signals sig;

    float fminf(float a, float b);
    float fmaxf(float a, float b);
    float clamp(float value, float min, float max);
    float midiToFreq(float midiNum);
    void fillWithValue(any array, unsigned long length, float value);
    void fillWithSilence(any array, unsigned long length);
    float interpolate_linear(float idx, any table,
        unsigned long length);
    float interpolate_cubic(float idx, any table,
        unsigned long length);
    float filter_onepole(float current, float previous, float coeff);
    float waveform_sine(float phase);
    float waveform_square(float phase);
    float waveform_saw(float phase);
    float waveform_reverseSaw(float phase);
    float waveform_triangle(float phase);

    star_Allocator Allocator_new(unsigned long heapSize);
    void Allocator_init(star_Allocator allocator);
    any Allocator_malloc(star_Allocator allocator, unsigned long size);
    void Allocator_free(star_Allocator allocator, any obj);

    star_AudioSettings AudioSettings_new(star_Allocator allocator);
    void AudioSettings_destroy(star_Allocator allocator,
        star_AudioSettings settings);

    star_Buffer Buffer_new(star_Allocator allocator,
        unsigned long length);
    void Buffer_fill(star_Buffer buffer, float value);
    void Buffer_fillWithSilence(star_Buffer buffer);
    void Buffer_destroy(star_Allocator allocator, star_Buffer buffer);

    any AudioBlock_new(star_Allocator allocator,
        star_AudioSettings audioSettings);
    any AudioBlock_newWithValue(star_Allocator allocator,
        star_AudioSettings audioSettings, float value);
};

interface star_Allocator {
    attribute unsigned long heapSize;
    attribute any heap;
};

interface star_AudioSettings {
    attribute float sampleRate;
    attribute unsigned long numChannels;
    attribute unsigned long blockSize;
};

interface star_Buffer {
    attribute unsigned long length;
    attribute any samples;
};

interface star_sig_Signal {
    attribute star_AudioSettings audioSettings;
    attribute any output;
    void generate(any signal);
};


interface star_sig_Value {
    [Value] attribute star_sig_Signal signal;
    [Value] attribute star_sig_Value_Parameters parameters;
    attribute float lastSample;
};

interface star_sig_Value_Parameters {
    attribute float value;
};


interface star_sig_Sine {
    [Value] attribute star_sig_Signal signal;
    attribute star_sig_Sine_Inputs inputs;
    attribute float phaseAccumulator;
};

interface star_sig_Sine_Inputs {
    attribute any freq;
    attribute any phaseOffset;
    attribute any mul;
    attribute any add;
};


interface star_sig_BinaryOp {
    [Value] attribute star_sig_Signal signal;
    attribute star_sig_BinaryOp_Inputs inputs;
};

interface star_sig_BinaryOp_Inputs {
    attribute any left;
    attribute any right;
};


interface star_sig_ClockFreqDetector {
    [Value] attribute star_sig_Signal signal;
    attribute star_sig_ClockFreqDetector_Inputs inputs;
};

interface star_sig_ClockFreqDetector_Inputs {
    attribute any source;
};
