interface Signals {
    void generateSignals(sig_List signalList);

    sig_dsp_Value Value_new(sig_Allocator allocator,
        sig_SignalContext context);

    void Value_destroy(sig_Allocator allocator,
        sig_dsp_Value value);


    sig_dsp_BinaryOp Mul_new(sig_Allocator allocator,
        sig_SignalContext context);

    void Mul_destroy(sig_Allocator allocator, sig_dsp_BinaryOp mul);

    sig_dsp_BinaryOp Add_new(sig_Allocator allocator,
        sig_SignalContext context);

    void Add_destroy(sig_Allocator allocator, sig_dsp_BinaryOp add);

    sig_dsp_BinaryOp Div_new(sig_Allocator allocator,
        sig_SignalContext context);

    void Div_destroy(sig_Allocator allocator, sig_dsp_BinaryOp div);


    sig_dsp_Oscillator Sine_new(sig_Allocator allocator,
        sig_SignalContext context);

    void Sine_destroy(sig_Allocator allocator,
        sig_dsp_Oscillator sine);

    sig_dsp_Oscillator LFTriangle_new(sig_Allocator allocator,
        sig_SignalContext context);

    void LFTriangle_destroy(sig_Allocator allocator,
        sig_dsp_Oscillator triangle);


    sig_dsp_ClockFreqDetector ClockFreqDetector_new(sig_Allocator allocator,
        sig_SignalContext context);

    void ClockFreqDetector_destroy(sig_Allocator allocator,
        sig_dsp_ClockFreqDetector detector);
};

interface Signaletic {
    readonly attribute float PI;
    readonly attribute float TWOPI;

    void Signaletic();

    [Value] attribute Signals dsp;

    sig_Status Status_new(sig_Allocator allocator);
    void Status_init(sig_Status status);
    void Status_reset(sig_Status status);
    void Status_reportResult(sig_Status status, sig_Result result);

    float fminf(float a, float b);
    float fmaxf(float a, float b);
    float clamp(float value, float min, float max);
    float midiToFreq(float midiNum);
    void fillWithValue(any array, unsigned long length, float value);
    void fillWithSilence(any array, unsigned long length);
    float interpolate_linear(float idx, any table,
        unsigned long length);
    float interpolate_cubic(float idx, any table,
        unsigned long length);
    float filter_onepole(float current, float previous, float coeff);
    float waveform_sine(float phase);
    float waveform_square(float phase);
    float waveform_saw(float phase);
    float waveform_reverseSaw(float phase);
    float waveform_triangle(float phase);

    sig_Allocator TLSFAllocator_new(unsigned long size);
    void TLSFAllocator_destroy(sig_Allocator allocator);

    sig_List List_new(sig_Allocator allocator,
        unsigned long capacity);
    void List_insert(sig_List list, unsigned long index, any item,
        sig_Status status);
    void List_append(sig_List list, any item, sig_Status status);
    any List_pop(sig_List list, sig_Status status);
    any List_remove(sig_List list, unsigned long index, sig_Status status);
    void List_destroy(sig_Allocator allocator, sig_List list);

    sig_AudioSettings AudioSettings_new(sig_Allocator allocator);
    void AudioSettings_destroy(sig_Allocator allocator,
        sig_AudioSettings audioSettings);

    sig_SignalContext SignalContext_new(sig_Allocator allocator,
        sig_AudioSettings audioSettings);
    void SignalContext_destroy(sig_Allocator allocator,
        sig_SignalContext signalContext);

    sig_Buffer Buffer_new(sig_Allocator allocator,
        unsigned long length);
    void Buffer_fill(sig_Buffer buffer, float value);
    void Buffer_fillWithSilence(sig_Buffer buffer);
    float Buffer_read(sig_Buffer buffer, float idx);
    float Buffer_readLinear(sig_Buffer buffer, float idx);
    float Buffer_readCubic(sig_Buffer buffer, float idx);
    void Buffer_destroy(sig_Allocator allocator, sig_Buffer buffer);

    any AudioBlock_new(sig_Allocator allocator,
        sig_AudioSettings audioSettings);
    any AudioBlock_newWithValue(sig_Allocator allocator,
        sig_AudioSettings audioSettings, float value);
    void AudioBlock_destroy(sig_Allocator allocator, any audioBlock);
};

enum sig_Result {
    "SIG_RESULT_NONE",
    "SIG_RESULT_SUCCESS",
    "SIG_ERROR_INDEX_OUT_OF_BOUNDS",
    "SIG_ERROR_EXCEEDS_CAPACITY"
};

interface sig_Status {
    attribute sig_Result result;
};

interface sig_AllocatorHeap {
    attribute unsigned long length;
    attribute any memory;
};

interface sig_AllocatorImpl {
    void init(sig_Allocator allocator);
    any malloc(sig_Allocator allocator, unsigned long size);
    void free(sig_Allocator allocator, any obj);
};

interface sig_Allocator {
    attribute sig_AllocatorImpl impl;
    attribute sig_AllocatorHeap heap;
};

interface sig_AudioSettings {
    attribute float sampleRate;
    attribute unsigned long numChannels;
    attribute unsigned long blockSize;
};

interface sig_Buffer {
    attribute unsigned long length;
    attribute any samples;
};

interface sig_List {
    attribute unsigned long capacity;
    attribute unsigned long length;
};

interface sig_dsp_Signal {
    attribute sig_AudioSettings audioSettings;
    attribute any output;
    void generate(any signal);
};

interface sig_dsp_ConstantValue {
    [Value] attribute sig_dsp_Signal signal;
};


interface sig_SignalContext {
    attribute sig_AudioSettings audioSettings;
    attribute sig_dsp_ConstantValue silence;
};

interface sig_dsp_Value {
    [Value] attribute sig_dsp_Signal signal;
    [Value] attribute sig_dsp_Value_Parameters parameters;
    attribute float lastSample;
};

interface sig_dsp_Value_Parameters {
    attribute float value;
};

interface sig_dsp_Oscillator_Inputs {
    attribute any freq;
    attribute any phaseOffset;
    attribute any mul;
    attribute any add;
};

interface sig_dsp_Oscillator {
    [Value] attribute sig_dsp_Signal signal;
    [Value] attribute sig_dsp_Oscillator_Inputs inputs;
    attribute float phaseAccumulator;
};


interface sig_dsp_BinaryOp {
    [Value] attribute sig_dsp_Signal signal;
    [Value] attribute sig_dsp_BinaryOp_Inputs inputs;
};

interface sig_dsp_BinaryOp_Inputs {
    attribute any left;
    attribute any right;
};


interface sig_dsp_ClockFreqDetector {
    [Value] attribute sig_dsp_Signal signal;
    [Value] attribute sig_dsp_ClockFreqDetector_Inputs inputs;
};

interface sig_dsp_ClockFreqDetector_Inputs {
    attribute any source;
};
